CynfoProject/Controllers/PlacesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using CynfoProject.Models;
using System.Security.Claims;

namespace CynfoProject.Controllers
{
    public class PlacesController : Controller
    {
        private GeneralDBContext db = new GeneralDBContext();

        // GET: Places
        public ActionResult Index()
        {
            Claim sessionUsername = ClaimsPrincipal.Current.FindFirst(ClaimTypes.Name);
            string username = sessionUsername.Value;
            var userIdQuery = db.UserAccounts.Where(u => u.Username == username).Select(u => u.UserID);
            var userId = userIdQuery.ToList()[0];

            return View(db.Places.Where(u => u.UserID == userId).ToList());
        }

        // GET: Places/Details/5
        public ActionResult Details(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Place place = db.Places.Find(id);
            if (place == null)
            {
                return HttpNotFound();
            }
            return View(place);
        }

        // GET: Places/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Places/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "PlaceID,PlaceName,PlaceDescription,PlaceLogoURL,PlaceMajor,PlaceAddress,Placecontact")] Place place)
        {
            if (ModelState.IsValid)
            {
                Claim sessionUsername = ClaimsPrincipal.Current.FindFirst(ClaimTypes.Name);
                string username = sessionUsername.Value;
                var userIdQuery = db.UserAccounts.Where(u => u.Username == username).Select(u => u.UserID);
                var userId = userIdQuery.ToList()[0];
                place.UserID = userId;
                db.Places.Add(place);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(place);
        }

        // GET: Places/Edit/5
        public ActionResult Edit(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Place place = db.Places.Find(id);
            if (place == null)
            {
                return HttpNotFound();
            }
            return View(place);
        }

        // POST: Places/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "PlaceID,PlaceName,PlaceDescription,PlaceLogoURL,PlaceMajor,PlaceAddress,Placecontact")] Place place)
        {
            if (ModelState.IsValid)
            {
                Claim sessionUsername = ClaimsPrincipal.Current.FindFirst(ClaimTypes.Name);
                string username = sessionUsername.Value;
                var userIdQuery = db.UserAccounts.Where(u => u.Username == username).Select(u => u.UserID);
                var userId = userIdQuery.ToList()[0];
                place.UserID = userId;
                db.Entry(place).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(place);
        }

        // GET: Places/Delete/5
        public ActionResult Delete(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Place place = db.Places.Find(id);
            if (place == null)
            {
                return HttpNotFound();
            }
            return View(place);
        }

        // POST: Places/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(string id)
        {
            Place place = db.Places.Find(id);
            db.Places.Remove(place);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

CynfoProject/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Cynfo", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>

            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("About", "About", "Home")</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                </ul>
                <ul class="nav navbar-nav navbar-right">
                    @if (@User.Identity.IsAuthenticated)
                    {
                        <li>@Html.ActionLink("Your are in " + @User.Identity.Name + "'s Domain", "Index", "Home")</li>
                        <li>@Html.ActionLink("My Places", "Index", "Places")</li>
                        <li>@Html.ActionLink("Logout", "Logout", "Auth")</li>
                    }
                    else
                    {
                        <li>@Html.ActionLink("Login", "Login", "Auth")</li>
                        <li>@Html.ActionLink("Register", "Register", "Auth")</li>
                    }
                </ul>

</div>
        </div>
    </div>


    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>